# shortcut to .dotfiles
export ZSH=$HOME/.dotfiles

# histfile and size
HISTFILE=~/.zsh_history
HISTSIZE=1000
SAVEHIST=1000

# initialize fonts and  source 'powerlevel9k' theme
POWERLEVEL9K_MODE='nerdfont-complete'
source  ~/.dotfiles/zsh/themes/powerlevel9k/powerlevel9k.zsh-theme

# configure 'powerlevel9k' theme
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(host user dir vcs newline)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(virtualenv)
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

# LSCOLOR
export CLICOLOR=1

# loop trough all our *.zsh files and source them
typeset -U alias_files
alias_files=($ZSH/**/*.alias)

for file in ${(M)alias_files}; do
  source $file
done

# load custom functions

for function in $ZSH/functions/*; do
  source $function
done
